using FluentAssertions;
using Moq;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Tokki.Application.Common.ExcelCore;
using Tokki.Application.Common.Models;
using Tokki.Application.UseCases.Excel.DTOs;
using Tokki.Application.UseCases.Excel.Queries.GetTemplate;
using Tokki.UnitTest.Utilities;
using Xunit;

namespace Tokki.UnitTest.Application.UseCases.Excel
{
    public class GetAccountTemplateQueryHandlerTests
    {
        private static GetAccountTemplateQueryHandler CreateHandler(Mock<IExcelBaseService>? excelService = null)
        {
            return new GetAccountTemplateQueryHandler((excelService ?? new Mock<IExcelBaseService>()).Object);
        }

        // GetAccountTemplate_01 | N | Check exact filename
        [Fact]
        public async Task Handle_ValidRequest_ShouldReturnExpectedFileName()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<AccountExcelDTO>("Template_Account")).ReturnsAsync(new byte[] { 1 });

            var result = await CreateHandler(mockExcel).Handle(new GetAccountTemplateQuery(), CancellationToken.None);

            result.IsSuccess.Should().BeTrue();
            result.Data.FileName.Should().Be("Template_Import_Account.xlsx");

            QACollector.LogTestCase("Excel - Get Account Template", new TestCaseDetail
            {
                FunctionGroup = "GetAccountTemplate", TestCaseID = "GetAccountTemplate_01",
                Description = "Handler strictly binds to target FileName for downloads",
                ExpectedResult = "Return 200, FileName == 'Template_Import_Account.xlsx'", StatusRound1 = "Passed", TestCaseType = "N",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "fileName constant check" }
            });
        }

        // GetAccountTemplate_02 | N | Check byte parsing bridging
        [Fact]
        public async Task Handle_ValidRequest_ShouldReturnProperFileBytes()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<AccountExcelDTO>("Template_Account")).ReturnsAsync(new byte[] { 0x0A, 0x0B });

            var result = await CreateHandler(mockExcel).Handle(new GetAccountTemplateQuery(), CancellationToken.None);

            result.IsSuccess.Should().BeTrue();
            result.Data.FileBytes.Should().Equal(new byte[] { 0x0A, 0x0B });

            QACollector.LogTestCase("Excel - Get Account Template", new TestCaseDetail
            {
                FunctionGroup = "GetAccountTemplate", TestCaseID = "GetAccountTemplate_02",
                Description = "Handler pipes ExcelBaseService raw generated bytes out to caller",
                ExpectedResult = "Return 200, FileBytes verified", StatusRound1 = "Passed", TestCaseType = "N",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "byte comparison" }
            });
        }

        // GetAccountTemplate_03 | N | Verify service called exactly once
        [Fact]
        public async Task Handle_ValidRequest_ShouldCallGenerateTemplateExactlyOnce()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<AccountExcelDTO>(It.IsAny<string>())).ReturnsAsync(new byte[] { 1 });

            await CreateHandler(mockExcel).Handle(new GetAccountTemplateQuery(), CancellationToken.None);

            mockExcel.Verify(x => x.GenerateTemplateAsync<AccountExcelDTO>(It.IsAny<string>()), Times.Once);

            QACollector.LogTestCase("Excel - Get Account Template", new TestCaseDetail
            {
                FunctionGroup = "GetAccountTemplate", TestCaseID = "GetAccountTemplate_03",
                Description = "Service must not be called redundantly, causing massive memory spikes",
                ExpectedResult = "Return 200, Times.Once validation on GenerateTemplateAsync", StatusRound1 = "Passed", TestCaseType = "N",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "Times.Once" }
            });
        }

        // GetAccountTemplate_04 | N | Check sheet name parameter mapping
        [Fact]
        public async Task Handle_ValidRequest_ShouldProvideCorrectSheetNameToService()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<AccountExcelDTO>("Template_Account")).ReturnsAsync(new byte[] { 1 });

            await CreateHandler(mockExcel).Handle(new GetAccountTemplateQuery(), CancellationToken.None);

            mockExcel.Verify(x => x.GenerateTemplateAsync<AccountExcelDTO>("Template_Account"), Times.Once);

            QACollector.LogTestCase("Excel - Get Account Template", new TestCaseDetail
            {
                FunctionGroup = "GetAccountTemplate", TestCaseID = "GetAccountTemplate_04",
                Description = "Ensure sheet name is correctly formulated before generating XML tree",
                ExpectedResult = "Return 200, verifies Template_Account argument", StatusRound1 = "Passed", TestCaseType = "N",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "Strict param match check 'Template_Account'" }
            });
        }

        // GetAccountTemplate_05 | A | Handle Exception from dependency -> graceful Failure
        [Fact]
        public async Task Handle_ExcelServiceThrows_ShouldReturnFailureResult()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<AccountExcelDTO>(It.IsAny<string>())).ThrowsAsync(new Exception("Stream Error"));

            var result = await CreateHandler(mockExcel).Handle(new GetAccountTemplateQuery(), CancellationToken.None);

            result.IsSuccess.Should().BeFalse();
            
            QACollector.LogTestCase("Excel - Get Account Template", new TestCaseDetail
            {
                FunctionGroup = "GetAccountTemplate", TestCaseID = "GetAccountTemplate_05",
                Description = "Library throws generic exception, gracefully wraps in MediatR result",
                ExpectedResult = "Return Failure", StatusRound1 = "Passed", TestCaseType = "A",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "catch (Exception)" }
            });
        }

        // GetAccountTemplate_06 | A | Handle Exception propagates the actual error message
        [Fact]
        public async Task Handle_ExcelServiceThrows_ShouldContainExceptionMessage()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<AccountExcelDTO>(It.IsAny<string>())).ThrowsAsync(new Exception("DLL NOT FOUND"));

            var result = await CreateHandler(mockExcel).Handle(new GetAccountTemplateQuery(), CancellationToken.None);

            result.Message.Should().Contain("DLL NOT FOUND");
            result.Errors![0].Code.Should().Be("TEMPLATE_ERROR");

            QACollector.LogTestCase("Excel - Get Account Template", new TestCaseDetail
            {
                FunctionGroup = "GetAccountTemplate", TestCaseID = "GetAccountTemplate_06",
                Description = "Ensure the exact system trace message is included alongside TEMPLATE_ERROR code",
                ExpectedResult = "Return Failure, payload string match", StatusRound1 = "Passed", TestCaseType = "A",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "Contains TEMPLATE_ERROR" }
            });
        }
    }
}