using FluentAssertions;
using Moq;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Tokki.Application.Common.ExcelCore;
using Tokki.Application.Common.Models;
using Tokki.Application.UseCases.Excel.DTOs;
using Tokki.Application.UseCases.Excel.Queries.TemplateQuestionType;
using Tokki.UnitTest.Utilities;
using Xunit;

namespace Tokki.UnitTest.Application.UseCases.Excel
{
    public class GetQuestionTypeTemplateQueryHandlerTests
    {
        private static GetQuestionTypeTemplateQueryHandler CreateHandler(Mock<IExcelBaseService>? excelService = null)
        {
            return new GetQuestionTypeTemplateQueryHandler((excelService ?? new Mock<IExcelBaseService>()).Object);
        }

        // TC-EXC-GQT-01 | N | Check exact filename
        [Fact]
        public async Task Handle_ValidRequest_ShouldReturnExpectedFileName()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<QuestionTypeExcelDTO>("Template_QuestionType")).ReturnsAsync(new byte[] { 1 });

            var result = await CreateHandler(mockExcel).Handle(new GetQuestionTypeTemplateQuery(), CancellationToken.None);

            result.IsSuccess.Should().BeTrue();
            result.Data.FileName.Should().Be("Template_Import_QuestionType.xlsx");

            QACollector.LogTestCase("Excel - Get QuestionType Template", new TestCaseDetail
            {
                FunctionGroup = "GetQuestionTypeTemplate", TestCaseID = "TC-EXC-GQT-01",
                Description = "Handler stringently binds strictly to explicit filename mapping string",
                ExpectedResult = "Return 200, string matches 'Template_Import_QuestionType.xlsx'", StatusRound1 = "Passed", TestCaseType = "N",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "fileName exact verification" }
            });
        }

        // TC-EXC-GQT-02 | N | Check byte parsing bridging
        [Fact]
        public async Task Handle_ValidRequest_ShouldReturnProperFileBytes()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<QuestionTypeExcelDTO>("Template_QuestionType")).ReturnsAsync(new byte[] { 0x1A, 0x1B });

            var result = await CreateHandler(mockExcel).Handle(new GetQuestionTypeTemplateQuery(), CancellationToken.None);

            result.IsSuccess.Should().BeTrue();
            result.Data.FileBytes.Should().Equal(new byte[] { 0x1A, 0x1B });

            QACollector.LogTestCase("Excel - Get QuestionType Template", new TestCaseDetail
            {
                FunctionGroup = "GetQuestionTypeTemplate", TestCaseID = "TC-EXC-GQT-02",
                Description = "Raw bytes generated by deep parser are correctly lifted and bound to MediatR response",
                ExpectedResult = "Return 200 FileBytes preserved exactly", StatusRound1 = "Passed", TestCaseType = "N",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "byte stream parsing continuity" }
            });
        }

        // TC-EXC-GQT-03 | N | Verify service called exactly once
        [Fact]
        public async Task Handle_ValidRequest_ShouldCallGenerateTemplateExactlyOnce()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<QuestionTypeExcelDTO>(It.IsAny<string>())).ReturnsAsync(new byte[] { 1 });

            await CreateHandler(mockExcel).Handle(new GetQuestionTypeTemplateQuery(), CancellationToken.None);

            mockExcel.Verify(x => x.GenerateTemplateAsync<QuestionTypeExcelDTO>(It.IsAny<string>()), Times.Once);

            QACollector.LogTestCase("Excel - Get QuestionType Template", new TestCaseDetail
            {
                FunctionGroup = "GetQuestionTypeTemplate", TestCaseID = "TC-EXC-GQT-03",
                Description = "Avoid repeated large allocations by ensuring template generation triggers 1 strictly",
                ExpectedResult = "Times.Once verified successfully", StatusRound1 = "Passed", TestCaseType = "N",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "mock framework Times.Once call tracking" }
            });
        }

        // TC-EXC-GQT-04 | N | Check sheet name parameter mapping
        [Fact]
        public async Task Handle_ValidRequest_ShouldProvideCorrectSheetNameToService()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<QuestionTypeExcelDTO>("Template_QuestionType")).ReturnsAsync(new byte[] { 1 });

            await CreateHandler(mockExcel).Handle(new GetQuestionTypeTemplateQuery(), CancellationToken.None);

            mockExcel.Verify(x => x.GenerateTemplateAsync<QuestionTypeExcelDTO>("Template_QuestionType"), Times.Once);

            QACollector.LogTestCase("Excel - Get QuestionType Template", new TestCaseDetail
            {
                FunctionGroup = "GetQuestionTypeTemplate", TestCaseID = "TC-EXC-GQT-04",
                Description = "Sheet tab target name explicitly enforced as 'Template_QuestionType'",
                ExpectedResult = "Method arg tracking parses out true against explicit const", StatusRound1 = "Passed", TestCaseType = "N",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "Verify with specific string string format parameter" }
            });
        }

        // TC-EXC-GQT-05 | A | Handle Exception from dependency
        [Fact]
        public async Task Handle_ExcelServiceThrows_ShouldReturnFailureResult()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<QuestionTypeExcelDTO>(It.IsAny<string>())).ThrowsAsync(new Exception("DLL Load Exception"));

            var result = await CreateHandler(mockExcel).Handle(new GetQuestionTypeTemplateQuery(), CancellationToken.None);

            result.IsSuccess.Should().BeFalse();
            
            QACollector.LogTestCase("Excel - Get QuestionType Template", new TestCaseDetail
            {
                FunctionGroup = "GetQuestionTypeTemplate", TestCaseID = "TC-EXC-GQT-05",
                Description = "Dependency errors out, triggering internal catch mechanism mapping to structured failure",
                ExpectedResult = "Return string indicating failure", StatusRound1 = "Passed", TestCaseType = "A",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "try-catch block intercepts downstream DLL error" }
            });
        }

        // TC-EXC-GQT-06 | A | Ensure TEMPLATE_ERROR format exists
        [Fact]
        public async Task Handle_ExcelServiceThrows_ShouldContainExceptionMessage()
        {
            var mockExcel = new Mock<IExcelBaseService>();
            mockExcel.Setup(x => x.GenerateTemplateAsync<QuestionTypeExcelDTO>(It.IsAny<string>())).ThrowsAsync(new Exception("File system lock"));

            var result = await CreateHandler(mockExcel).Handle(new GetQuestionTypeTemplateQuery(), CancellationToken.None);

            result.Message.Should().Contain("File system lock");
            result.Errors![0].Code.Should().Be("TEMPLATE_ERROR");

            QACollector.LogTestCase("Excel - Get QuestionType Template", new TestCaseDetail
            {
                FunctionGroup = "GetQuestionTypeTemplate", TestCaseID = "TC-EXC-GQT-06",
                Description = "Assert formatted code is exactly TEMPLATE_ERROR combined with system string payload",
                ExpectedResult = "Message concatenates target tokens appropriately", StatusRound1 = "Passed", TestCaseType = "A",
                TestDate = DateTime.Now.ToString("dd/MM/yyyy"),
                AppliedConditions = new List<string> { "result message structure matching template" }
            });
        }
    }
}
