using DnsClient.Internal;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Tokki.Application.Common.Models;
using Tokki.Application.IServices;
using Tokki.Application.UseCases.Exam.Commands.CreateExam;
using Tokki.Application.UseCases.ExamTemplates.Commands.AddTemplateParts;
using Tokki.Application.UseCases.ExamTemplates.Commands.CreateExamTemplate;
using Tokki.Application.UseCases.ExamTemplates.DTOs;
using Tokki.Domain.Entities;
using Tokki.Domain.Enums;
using Tokki.Infrastructure.Data;

namespace Tokki.Infrastructure.Services
{
    public class ExamAssemblyService : IExamAssemblyService
    {
        private readonly IMediator _mediator;
        private readonly TokkiDbContext _context;
        private readonly IIdGeneratorService _idGenerator;
        private const string AI_SYSTEM_ID = "AI_EXAM_SYSTEM"; 


        private const int QUESTIONS_PER_PART_MCQ = 10;
        private const int QUESTIONS_PER_PART_WRITING = 2;
        private readonly ILogger<ExamAssemblyService> _logger; 
        public ExamAssemblyService(
            IMediator mediator,
            TokkiDbContext context,
            IIdGeneratorService idGenerator,
            ILogger<ExamAssemblyService> logger)
        {
            _mediator = mediator;
            _context = context;
            _idGenerator = idGenerator;
            _logger = logger;
        }
        public async Task<OperationResult<string>> GenerateWeeklyExamFromScopeAsync(
            string userId,
            int weekIndex,
            List<string> weeklyQuestionTypeIds,
            ExamType examType,
            CancellationToken cancellationToken = default)
        {
            var targetTypes = weeklyQuestionTypeIds.Distinct().OrderBy(x => x).ToList();
            if (!targetTypes.Any())
                return OperationResult<string>.Failure("Không có dạng bài nào để tạo đề.", 400);

            var questionTypes = await _context.QuestionTypes
                .Where(qt => targetTypes.Contains(qt.QuestionTypeId))
                .ToListAsync(cancellationToken);

            var qtMap = questionTypes.ToDictionary(qt => qt.QuestionTypeId);
            string structureHash = string.Join("|", targetTypes);
            string templateIdToUse;

            var existingStructure = await _context.ExamTemplateStructures
                .AsNoTracking()
                .Include(x => x.ExamTemplate)
                .FirstOrDefaultAsync(x => x.StructureHash == structureHash, cancellationToken);

            bool canReuse = existingStructure != null
                && existingStructure.ExamTemplate != null
                && existingStructure.ExamTemplate.Type == examType
                && existingStructure.ExamTemplate.Status == ExamTemplateStatus.Published;

            if (canReuse)
            {
                templateIdToUse = existingStructure!.ExamTemplateId;
                _logger.LogInformation(
                    "Tái sử dụng template {TemplateId} cho scope [{Scope}]",
                    templateIdToUse, structureHash);
            }
            else
            {
                if (existingStructure != null)
                {
                    _logger.LogWarning(
                        "Template {TemplateId} không hợp lệ (ExamType mismatch hoặc chưa Published). Tạo lại template mới.",
                        existingStructure.ExamTemplateId);
                    _context.ExamTemplateStructures.Remove(existingStructure);
                    await _context.SaveChangesAsync(cancellationToken);
                }

                string examTypeLabel = examType == ExamType.TopikI ? "TOPIK I" : "TOPIK II";
                var codeParts = targetTypes
                    .Select(id => qtMap.TryGetValue(id, out var qt)
                        ? (qt.Code ?? qt.Name)
                        : id);
                string templateName = $"[WEEKLY] {examTypeLabel} | {string.Join(" · ", codeParts)}";

                var createTemplateCmd = new CreateExamTemplateCommand
                {
                    Name = templateName,
                    Description = "Auto-generated by Adaptive Learning System",
                    Type = examType,
                    CreatedBy = AI_SYSTEM_ID
                };

                var templateResult = await _mediator.Send(createTemplateCmd, cancellationToken);
                if (!templateResult.IsSuccess)
                    return OperationResult<string>.Failure($"Lỗi tạo Template: {templateResult.Message}");

                string newTemplateId = templateResult.Data;

                var partsDto = new List<CreateTemplatePartDto>();
                int currentQ = 1;

                var orderedTypes = targetTypes
                    .OrderBy(id => qtMap.TryGetValue(id, out var qt) ? (int)qt.Skill : 99);

                foreach (var typeId in orderedTypes)
                {
                    qtMap.TryGetValue(typeId, out var qType);
                    QuestionSkill skill = qType?.Skill ?? QuestionSkill.Reading;

                    int questionsForType = skill == QuestionSkill.Writing
                        ? QUESTIONS_PER_PART_WRITING
                        : QUESTIONS_PER_PART_MCQ;

                    int markPerQuestion = skill == QuestionSkill.Writing ? 10 : 2;

                    partsDto.Add(new CreateTemplatePartDto
                    {
                        PartTitle = qType?.Name ?? typeId,
                        QuestionTypeId = typeId,
                        Skill = skill,
                        QuestionFrom = currentQ,
                        QuestionTo = currentQ + questionsForType - 1,
                        Mark = markPerQuestion,
                        Instruction = skill == QuestionSkill.Writing
                            ? "Hãy viết bài theo yêu cầu."
                            : "Choose the best answer."
                    });
                    currentQ += questionsForType;
                }

                var addPartsResult = await _mediator.Send(
                    new AddTemplatePartsCommand { ExamTemplateId = newTemplateId, Parts = partsDto },
                    cancellationToken);

                if (!addPartsResult.IsSuccess)
                    return OperationResult<string>.Failure($"Lỗi tạo parts: {addPartsResult.Message}");

                var tpl = await _context.ExamTemplates.FindAsync(newTemplateId);
                if (tpl != null) tpl.Status = ExamTemplateStatus.Published;

                _context.ExamTemplateStructures.Add(new ExamTemplateStructure
                {
                    Id = _idGenerator.GenerateCustom(15),
                    StructureHash = structureHash,
                    ExamTemplateId = newTemplateId,
                    CreatedAt = DateTime.UtcNow
                });

                await _context.SaveChangesAsync(cancellationToken);
                templateIdToUse = newTemplateId;
                _logger.LogInformation(
                    "Tạo template mới {TemplateId} ({Name}) cho scope [{Scope}]",
                    newTemplateId, templateName, structureHash);
            }

            int duration = targetTypes.Sum(id =>
                qtMap.TryGetValue(id, out var qt) && qt.Skill == QuestionSkill.Writing ? 20 : 10);

            string examTitle = $"Weekly Exam W{weekIndex} - {userId[..Math.Min(6, userId.Length)]} - {DateTime.UtcNow:ddMMHHmmss}";

            var createExamCmd = new CreateExamCommand
            {
                Title = examTitle,
                ExamTemplateId = templateIdToUse,
                CreatedBy = AI_SYSTEM_ID
            };

            var examResult = await _mediator.Send(createExamCmd, cancellationToken);

            if (examResult.IsSuccess)
            {
                var exam = await _context.Exams.FindAsync(examResult.Data);
                if (exam != null)
                {
                    exam.Status = ExamStatus.Published;
                    await _context.SaveChangesAsync(cancellationToken);
                }
                _logger.LogInformation(
                    "Tạo weekly exam {ExamId} tuần {Week} thành công (Published).", examResult.Data, weekIndex);
            }
            else
            {
                _logger.LogError(
                    "Tạo weekly exam tuần {Week} thất bại: {Msg}", weekIndex, examResult.Message);
            }

            return examResult;
        }
        public async Task<OperationResult<string>> GenerateWeeklyExamAsync(
            string templateId,
            string userId,
            int weekIndex,
            List<string> weakQuestionTypeIds,
            DifficultyLevel targetLevel,
            CancellationToken cancellationToken = default)
        {
            return OperationResult<string>.Failure("Deprecated method");
        }
        public async Task<(bool IsValid, List<string> InsufficientTypes)> ValidateQuestionAvailabilityAsync(
            List<string> questionTypeIds,
            CancellationToken cancellationToken = default)
        {
            var insufficientTypes = new List<string>();

            foreach (var typeId in questionTypeIds)
            {
                var qType = await _context.QuestionTypes
                    .AsNoTracking()
                    .FirstOrDefaultAsync(q => q.QuestionTypeId == typeId, cancellationToken);

                if (qType == null) continue;

                int required = qType.Skill == QuestionSkill.Writing
                    ? QUESTIONS_PER_PART_WRITING
                    : QUESTIONS_PER_PART_MCQ;

                int available = await _context.QuestionBank
                    .CountAsync(q => q.QuestionTypeId == typeId
                                  && q.Status == QuestionBankStatus.Active
                                  && q.QuestionType.Difficulty == qType.Difficulty,
                        cancellationToken);

                if (available < required)
                {
                    insufficientTypes.Add(typeId);
                    _logger.LogWarning(
                        "QuestionType {TypeId} (Skill={Skill}, Difficulty={Diff}): cần {Required} câu, chỉ có {Available} câu active.",
                        typeId, qType.Skill, qType.Difficulty, required, available);
                }
            }

            return (!insufficientTypes.Any(), insufficientTypes);
        }
    }
}