using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Tokki.Application.Common.Models;
using Tokki.Application.IServices;
using Tokki.Application.UseCases.Exam.Commands.CreateExam;
using Tokki.Application.UseCases.ExamTemplates.Commands.AddTemplateParts;
using Tokki.Application.UseCases.ExamTemplates.Commands.CreateExamTemplate;
using Tokki.Application.UseCases.ExamTemplates.DTOs;
using Tokki.Domain.Entities; 
using Tokki.Domain.Enums;
using Tokki.Infrastructure.Data;

namespace Tokki.Infrastructure.Services
{
    public class ExamAssemblyService : IExamAssemblyService
    {
        private readonly IMediator _mediator;
        private readonly TokkiDbContext _context;
        private readonly IIdGeneratorService _idGenerator;
        private const string AI_SYSTEM_ID = "AI_SYSTEM_ACCOUNT";
        private const int QUESTIONS_PER_PART_MCQ = 10;
        private const int QUESTIONS_PER_PART_WRITING = 2;
        private readonly ILogger<ExamAssemblyService> _logger; 
        public ExamAssemblyService(
            IMediator mediator,
            TokkiDbContext context,
            IIdGeneratorService idGenerator,
            ILogger<ExamAssemblyService> logger)
        {
            _mediator = mediator;
            _context = context;
            _idGenerator = idGenerator;
            _logger = logger;
        }
        public async Task<OperationResult<string>> GenerateWeeklyExamFromScopeAsync(
            string userId,
            int weekIndex,
            List<string> weeklyQuestionTypeIds,
            ExamType examType,          
            CancellationToken cancellationToken = default)
        {
            var targetTypes = weeklyQuestionTypeIds.Distinct().OrderBy(x => x).ToList();
            if (!targetTypes.Any())
                return OperationResult<string>.Failure("Không có dạng bài nào để tạo đề.", 400);

            string structureHash = string.Join("|", targetTypes);
            string templateIdToUse;

            var existingStructure = await _context.ExamTemplateStructures
                .AsNoTracking()
                .FirstOrDefaultAsync(x => x.StructureHash == structureHash, cancellationToken);

            if (existingStructure != null)
            {
                templateIdToUse = existingStructure.ExamTemplateId;
            }
            else
            {
                string templateName = $"AI Weekly: {Math.Abs(structureHash.GetHashCode()):X8}";

                var createTemplateCmd = new CreateExamTemplateCommand
                {
                    Name = templateName,
                    Description = "Auto-generated by Adaptive Learning System",
                    Type = examType,        
                    CreatedBy = AI_SYSTEM_ID
                };

                var templateResult = await _mediator.Send(createTemplateCmd, cancellationToken);
                if (!templateResult.IsSuccess)
                    return OperationResult<string>.Failure($"Lỗi tạo Template: {templateResult.Message}");

                string newTemplateId = templateResult.Data;

                var partsDto = new List<CreateTemplatePartDto>();
                int currentQ = 1;

                foreach (var typeId in targetTypes)
                {
                    var qType = await _context.QuestionTypes.FindAsync(typeId);
                    QuestionSkill skill = qType?.Skill ?? QuestionSkill.Reading;

                    int questionsForType = skill == QuestionSkill.Writing
                        ? QUESTIONS_PER_PART_WRITING
                        : QUESTIONS_PER_PART_MCQ;

                    int markPerQuestion = skill == QuestionSkill.Writing ? 10 : 2;

                    string partTitle = qType?.Name ?? typeId;

                    partsDto.Add(new CreateTemplatePartDto
                    {
                        PartTitle = partTitle,
                        QuestionTypeId = typeId,
                        Skill = skill,
                        QuestionFrom = currentQ,
                        QuestionTo = currentQ + questionsForType - 1,
                        Mark = markPerQuestion,
                        Instruction = skill == QuestionSkill.Writing
                            ? "Hãy viết bài theo yêu cầu."
                            : "Choose the best answer."
                    });
                    currentQ += questionsForType;
                }

                var addPartsCmd = new AddTemplatePartsCommand
                {
                    ExamTemplateId = newTemplateId,
                    Parts = partsDto
                };

                var addPartsResult = await _mediator.Send(addPartsCmd, cancellationToken);
                if (!addPartsResult.IsSuccess)
                    return OperationResult<string>.Failure($"Lỗi tạo parts: {addPartsResult.Message}");

                var tpl = await _context.ExamTemplates.FindAsync(newTemplateId);
                if (tpl != null) tpl.Status = ExamTemplateStatus.Published;

                _context.ExamTemplateStructures.Add(new ExamTemplateStructure
                {
                    Id = _idGenerator.GenerateCustom(15),
                    StructureHash = structureHash,
                    ExamTemplateId = newTemplateId,
                    CreatedAt = DateTime.UtcNow
                });

                await _context.SaveChangesAsync(cancellationToken);
                templateIdToUse = newTemplateId;
            }

            string examTitle = $"Weekly Exam W{weekIndex} - {userId[..6]} - {DateTime.UtcNow:ddMMHHmmss}";

            var createExamCmd = new CreateExamCommand
            {
                Title = examTitle,
                Duration = targetTypes.Count * 10,
                ExamTemplateId = templateIdToUse,
                CreatedBy = AI_SYSTEM_ID
            };

            var examResult = await _mediator.Send(createExamCmd, cancellationToken);
            return examResult;
        }
        public async Task<OperationResult<string>> GenerateWeeklyExamAsync(
           string templateId,
           string userId,
           int weekIndex,
           List<string> weakQuestionTypeIds,
           DifficultyLevel targetLevel,
           CancellationToken cancellationToken = default)
        {
            return OperationResult<string>.Failure("Deprecated method");
        }
        public async Task<(bool IsValid, List<string> InsufficientTypes)> ValidateQuestionAvailabilityAsync(
            List<string> questionTypeIds,
            CancellationToken cancellationToken = default)
        {
            var insufficientTypes = new List<string>();

            foreach (var typeId in questionTypeIds)
            {
                var qType = await _context.QuestionTypes
                    .AsNoTracking()
                    .FirstOrDefaultAsync(q => q.QuestionTypeId == typeId, cancellationToken);

                if (qType == null) continue;

                int required = qType.Skill == QuestionSkill.Writing
                    ? QUESTIONS_PER_PART_WRITING
                    : QUESTIONS_PER_PART_MCQ;

                int available = await _context.QuestionBank
                    .CountAsync(q => q.QuestionTypeId == typeId, cancellationToken);

                if (available < required)
                {
                    insufficientTypes.Add(typeId);
                    _logger.LogWarning(
                        "QuestionType {TypeId} không đủ câu: cần {Required}, có {Available}",
                        typeId, required, available);
                }
            }

            return (!insufficientTypes.Any(), insufficientTypes);
        }
    }
}