using MediatR;
using Microsoft.EntityFrameworkCore;
using Tokki.Application.Common.Models;
using Tokki.Application.IServices;
using Tokki.Application.UseCases.Exam.Commands.CreateExam;
using Tokki.Application.UseCases.ExamTemplates.Commands.AddTemplateParts;
using Tokki.Application.UseCases.ExamTemplates.Commands.CreateExamTemplate;
using Tokki.Application.UseCases.ExamTemplates.DTOs;
using Tokki.Domain.Entities; 
using Tokki.Domain.Enums;
using Tokki.Infrastructure.Data;

namespace Tokki.Infrastructure.Services
{
    public class ExamAssemblyService : IExamAssemblyService
    {
        private readonly IMediator _mediator;
        private readonly TokkiDbContext _context;
        private readonly IIdGeneratorService _idGenerator;
        private const string AI_SYSTEM_ID = "AI_SYSTEM_ACCOUNT";
        private const int QUESTIONS_PER_PART = 10;

        public ExamAssemblyService(
            IMediator mediator,
            TokkiDbContext context,
            IIdGeneratorService idGenerator)
        {
            _mediator = mediator;
            _context = context;
            _idGenerator = idGenerator;
        }
        public async Task<OperationResult<string>> GenerateWeeklyExamFromScopeAsync(
            string userId,
            int weekIndex,
            List<string> weeklyQuestionTypeIds,
            CancellationToken cancellationToken = default)
        {
            var targetTypes = weeklyQuestionTypeIds.Distinct().OrderBy(x => x).ToList();
            if (!targetTypes.Any()) return OperationResult<string>.Failure("Không có dạng bài nào để tạo đề.", 400);
            string structureHash = string.Join("|", targetTypes);

            string templateIdToUse;

            var existingStructure = await _context.ExamTemplateStructures
                .AsNoTracking()
                .FirstOrDefaultAsync(x => x.StructureHash == structureHash, cancellationToken);

            if (existingStructure != null)
            {
                templateIdToUse = existingStructure.ExamTemplateId;
            }
            else
            {
                string templateName = $"AI Auto-Gen: {structureHash.GetHashCode()} (Week {weekIndex})"; // Tên ngắn gọn

                var createTemplateCmd = new CreateExamTemplateCommand
                {
                    Name = templateName,
                    Description = "Auto-generated by Adaptive Learning System",
                    Type = ExamType.WeeklyAssessment, 
                    CreatedBy = AI_SYSTEM_ID 
                };

                var templateResult = await _mediator.Send(createTemplateCmd, cancellationToken);
                if (!templateResult.IsSuccess) return OperationResult<string>.Failure($"Lỗi tạo Template: {templateResult.Message}");

                string newTemplateId = templateResult.Data;

                var partsDto = new List<CreateTemplatePartDto>();
                int currentQ = 1;

                foreach (var typeId in targetTypes)
                {
                    var qType = await _context.QuestionTypes.FindAsync(typeId);
                    QuestionSkill skill = qType?.Skill ?? QuestionSkill.Reading;

                    partsDto.Add(new CreateTemplatePartDto
                    {
                        PartTitle = $"Section: {typeId}",
                        QuestionTypeId = typeId,
                        Skill = skill,
                        QuestionFrom = currentQ,
                        QuestionTo = currentQ + QUESTIONS_PER_PART - 1,
                        Mark = 1,
                        Instruction = "Choose the best answer."
                    });
                    currentQ += QUESTIONS_PER_PART;
                }

                var addPartsCmd = new AddTemplatePartsCommand
                {
                    ExamTemplateId = newTemplateId,
                    Parts = partsDto
                };
                await _mediator.Send(addPartsCmd, cancellationToken);

                var tpl = await _context.ExamTemplates.FindAsync(newTemplateId);
                if (tpl != null)
                {
                    tpl.Status = ExamTemplateStatus.Published;
                }

                var newStructureRecord = new ExamTemplateStructure
                {
                    Id = _idGenerator.GenerateCustom(15),
                    StructureHash = structureHash,
                    ExamTemplateId = newTemplateId,
                    CreatedAt = DateTime.UtcNow
                };

                _context.ExamTemplateStructures.Add(newStructureRecord);
                await _context.SaveChangesAsync(cancellationToken); 

                templateIdToUse = newTemplateId;
            }

            var createExamCmd = new CreateExamCommand
            {
                Title = $"Weekly Exam - Week {weekIndex} - {DateTime.UtcNow:dd/MM}",
                Duration = targetTypes.Count * 10, 
                ExamTemplateId = templateIdToUse,
                CreatedBy = AI_SYSTEM_ID
            };

            var examResult = await _mediator.Send(createExamCmd, cancellationToken);
            return examResult;
        }
        public async Task<OperationResult<string>> GenerateWeeklyExamAsync(
           string templateId,
           string userId,
           int weekIndex,
           List<string> weakQuestionTypeIds,
           DifficultyLevel targetLevel,
           CancellationToken cancellationToken = default)
        {
            return OperationResult<string>.Failure("Deprecated method");
        }
    }
}